// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvbmjtygrrtdninlpmsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12Ym1qdHlncnJ0ZG5pbmxwbXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzAyOTksImV4cCI6MjA2MjIwNjI5OX0.wf9vNPcQ-q83Uv62PIYc-NiYR2rK16fW0YMczHPoB4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);